{% set name = "loralib" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/loralib-{{ version }}.tar.gz
  sha256: 22ccff494a6254b973ddaee9f9aad4657941cab4221c75c5a04e0cac4fbd4567

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch

test:
  imports:
    - loralib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/LoRA
  summary: PyTorch implementation of low-rank adaptation (LoRA), a parameter-efficient approach to adapt a large pre-trained deep learning model which obtains performance on-par with full model fine-tuning.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - hadim
