context:
  name: loralib
  version: 0.1.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/loralib-${{ version }}.tar.gz
  sha256: 22ccff494a6254b973ddaee9f9aad4657941cab4221c75c5a04e0cac4fbd4567

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pytorch

tests:
  - python:
      imports:
        - loralib
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: PyTorch implementation of low-rank adaptation (LoRA), a parameter-efficient approach to adapt a large pre-trained deep learning model which obtains performance on-par with full model fine-tuning.
  license: MIT
  license_file: LICENSE.md
  homepage: https://github.com/microsoft/LoRA

extra:
  recipe-maintainers:
    - hadim
